import UnitCategoryPage, { commonFaqs } from "@/components/UnitCategoryPage";

const MedicalForRent = () => (
  <UnitCategoryPage
    heroLabel="Medical Units"
    heroTitle="Medical Units for Rent in Shorouk City"
    heroDescription="Find premium medical units for rent in Shorouk City. ASWAQ Developments offers modern clinics for rent at City Hub and Mercado Mall. Fully serviced medical properties starting from 30 m²."
    introTitle="The Ideal Setting for Medical Units"
    introDescription="Explore premium clinics for rent in East Cairo. ASWAQ Developments offers specialized medical units for rent that combine professional prestige with practical functionality. Renting a medical unit allows healthcare professionals to operate in prime locations without the commitment of ownership."
    locationTitle="Shorouk City: A Smart Location for Medical Units"
    locationDescription="As Shorouk City continues to expand, the need for accessible medical services in residential and business districts also grows."
    locationDrivers={[
      "Rising population density across residential compounds",
      "Increasing demand for nearby healthcare and specialty clinics",
      "Preference for medical services within organized commercial destinations",
      "Strong foot traffic generated by mixed-use real estate projects",
    ]}
    locationConclusion="This makes medical properties for rent in Shorouk City a practical and sustainable choice."
    mallsSectionTitle="Best Medical Units for Rent at ASWAQ Malls"
    mallsSectionIntro="Our medical units are strategically positioned within our flagship malls to ensure maximum accessibility."
    malls={[
      { name: "City Hub Mall", href: "/projects/city-hub-mall", description: "Perfect for practitioners seeking a high-end, modern atmosphere. Located across from the Shorouk and City Clubs, this location attracts a premium demographic looking for quality healthcare services.", sizes: "Spaces from 30 m² to 300 m²" },
      { name: "Mercado Mall", href: "/projects/mercado-mall", description: "As one of the largest fully-serviced complexes in the area, Mercado Mall offers a dedicated environment for medical professionals. These units benefit from the mall's existing footfall and community reputation.", sizes: "Spaces from 30 m² to 300 m²" },
    ]}
    ctaTitle="Ready to Secure your Medical Unit?"
    ctaSubtitle="Contact us now to explore available units, pricing details, and rental opportunities tailored to your needs."
    faqs={commonFaqs}
  />
);

export default MedicalForRent;
