import UnitCategoryPage, { commonFaqs } from "@/components/UnitCategoryPage";

const MedicalForSale = () => (
  <UnitCategoryPage
    metaTitle="Medical Units for Sale in Shorouk City | ASWAQ Developments"
    metaDescription="Own medical units for sale in Shorouk City with ASWAQ Developments. Discover clinics for sale within strategic real estate projects built for healthcare services."
    heroLabel="Medical Units"
    heroTitle="Medical Units for Sale in Shorouk City"
    heroDescription="Own medical units for sale in Shorouk City with ASWAQ Developments. Discover clinics for sale within strategic real estate projects built for healthcare services."
    introTitle="ASWAQ Real Estate Projects: The Ideal Setting for Medical Units"
    introDescription="Explore premium clinics for sale inside professionally planned real estate projects designed to support clinics and healthcare providers. ASWAQ Developments offers specialized medical units for sale that combine professional prestige with practical functionality. Owning a medical unit offers long-term stability, asset appreciation, and operational independence for healthcare professionals."
    locationTitle="Shorouk City: A Smart Location for Medical Units"
    locationDescription="As Shorouk City continues to expand, the need for accessible medical services in residential and business districts also grows."
    locationDrivers={[
      "Rising population density across residential compounds",
      "Increasing demand for nearby healthcare and specialty clinics",
      "Preference for medical services within organized commercial destinations",
      "Strong foot traffic generated by mixed-use real estate projects",
    ]}
    locationConclusion="This makes medical units for sale in Shorouk City a practical and sustainable choice."
    mallsSectionTitle="Best Medical Units for Sale at ASWAQ Malls"
    mallsSectionIntro="We specialize in creating vibrant destinations that blend retail, medical, and professional services. Our medical units are strategically positioned within our flagship malls."
    malls={[
      { name: "City Hub Mall", href: "/projects/city-hub-mall", description: "Perfect for practitioners seeking a high-end, modern atmosphere. Located in the Club District, these clinics for sale offer a sophisticated environment that reflects the quality of your medical services.", sizes: "Spaces from 30 m² to 300 m²" },
      { name: "Mercado Mall", href: "/projects/mercado-mall", description: "Secure a medical unit for sale in one of Shorouk's largest service hubs. Owning a unit here puts you at the center of a high-density residential area, ensuring your practice is a community landmark.", sizes: "Spaces from 30 m² to 300 m²" },
    ]}
    ctaTitle="Ready to Secure your Medical Unit?"
    ctaSubtitle="Contact us now to explore available units, pricing details, and investment opportunities tailored to your business goals."
    faqs={commonFaqs}
  />
);

export default MedicalForSale;
