import UnitCategoryPage, { commonFaqs } from "@/components/UnitCategoryPage";

const MedicalForInvestment = () => (
  <UnitCategoryPage
    heroLabel="Medical Units"
    heroTitle="Medical Units for Investment in Shorouk City"
    heroDescription="Capitalize on high-growth medical units for investment with ASWAQ Developments. Explore modern clinics & premium healthcare spaces from 30 m² in prime Shorouk City locations."
    introTitle="Own your Medical Unit for Investment"
    introDescription="Explore premium clinics for investment in East Cairo. ASWAQ Developments addresses the increasing need for professional healthcare environments by offering medical units for investment in the heart of Shorouk City. By integrating specialized medical floors into our mixed-use real estate projects, we provide a unique synergy where patient convenience meets high investor ROI."
    locationTitle="Shorouk City: A Smart Location for Medical Units"
    locationDescription="As Shorouk City continues to expand, the need for accessible medical services in residential and business districts also grows."
    locationDrivers={[
      "Rising population density across residential compounds",
      "Increasing demand for nearby healthcare and specialty clinics",
      "Preference for medical services within organized commercial destinations",
      "Strong foot traffic generated by mixed-use real estate projects",
    ]}
    locationConclusion="These factors make medical properties for investment in Shorouk City a future-proof choice."
    mallsSectionTitle="Best Medical Units for Investment at ASWAQ Malls"
    mallsSectionIntro="Our medical units are strategically positioned within our flagship malls to ensure maximum accessibility."
    malls={[
      { name: "City Hub Mall", href: "/projects/city-hub-mall", description: "Located in the heart of the Club District, City Hub is a landmark of modern architecture. Facing the Shorouk and City Clubs, its central location ensures that your medical property is easily accessible to thousands of families.", sizes: "Spaces from 30 m² to 300 m²" },
      { name: "Mercado Mall", href: "/projects/mercado-mall", description: "As one of the largest fully-serviced complexes in the area, Mercado Mall offers a dedicated environment for medical professionals. These clinics for investment benefit from the mall's existing footfall and community reputation.", sizes: "Spaces from 30 m² to 300 m²" },
    ]}
    ctaTitle="Ready to Secure your Medical Unit?"
    ctaSubtitle="Contact us now to explore available units, pricing details, and investment opportunities tailored to your goals."
    faqs={commonFaqs}
  />
);

export default MedicalForInvestment;
